#!/bin/bash
# Build self-contained, compile-ready submission ZIPs for the v21 round:
# main = journal_manuscript_v18.tex (JTB alignment), companion =
# companion_categorical_v10.tex (TAC, unchanged).
# Changes vs build_submission_zips_v20.sh (v17/BMB round):
#   - Main: new versioned file journal_manuscript_v18.tex built from v17
#     by scripts/v18_jtb_alignment.py per the JTB-alignment directive:
#     abstract trimmed 254 -> 249 audit-style words under JTB's 250-word
#     cap; keywords 6 -> 7 ('path dependence' added; JTB range 1-7);
#     CRediT authorship contribution statement (JTB-required taxonomy);
#     venue-neutral refs file journal_manuscript_v18_refs.tex (29 entries,
#     byte-identical to the v17 list); header retargeted BMB -> JTB.
#   - Highlights (JTB-required separate editable file):
#     download/highlights_jtb.docx (5 bullets, each <= 85 characters incl.
#     spaces, featuring biological applications + theoretical advances),
#     generated by scripts/v18_make_highlights.js, postcheck 9/9.
#   - Main package renamed submission_main_bmb.zip -> submission_main_jtb.zip
#     (venue decision: JTB primary per download/V17_Venue_Evaluation.md);
#     the ZIP itself remains venue-neutral and compiles identically for any
#     Elsevier/Springer target.
#   - Companion: unchanged (companion_categorical_v10.tex, TAC route).
#   - All numerical claims re-verified: audit_v26_numbers.py 347/347 PASS
#     (344 carried + 3 new JTB gates); pattern_sweep_v16 16/16 clean on
#     both; verify_v18_completeness.py ALL COMPLETE; tectonic 38 pp, 0
#     errors / 0 undefined / 0 '??'; clickable mailto + ORCID via qpdf;
#     VLM CLEAN on the changed pages (p1 abstract/keywords, p37 CRediT).
# Each ZIP verified by fresh-dir tectonic compile.
set -euo pipefail
cd /home/z/my-project/metabolic-curvature-measure

STAGE=scripts/overleaf_stage_v21
rm -rf "$STAGE"
mkdir -p "$STAGE/main" "$STAGE/companion"

# ---------- MAIN (Journal of Theoretical Biology) ----------
M=$STAGE/main
cp scripts/journal_manuscript_v18.tex          "$M/"
cp scripts/journal_manuscript_v18_refs.tex      "$M/"
cp scripts/journal_manuscript_v18_refs.bib      "$M/"
mkdir -p "$M/m1_m3" "$M/alexandrov_bridge" "$M/association_robustness"
cp download/m1_m3/fig_m1_summary.png                    "$M/m1_m3/"
cp download/alexandrov_bridge/coupling_figures.png      "$M/alexandrov_bridge/"
cp download/association_robustness/v5_e24_recalibration.png    "$M/association_robustness/"
cp download/association_robustness/v7_path_robustness.png      "$M/association_robustness/"
cp download/association_robustness/v8_tiebreak_robustness.png  "$M/association_robustness/"
cp download/association_robustness/e32_event_measure_stabilization.png "$M/association_robustness/"
cat > "$M/README.md" << 'EOF'
# Main manuscript — Journal of Theoretical Biology (Elsevier)
# Compile-ready standalone package

Title: A Geometric Theory of Metabolic Flux Rerouting: How Active-Set
Curvature Predicts Transcriptional Regulation and Protein-Layer
Buffering

## How to compile
- Overleaf: upload this ZIP via New Project -> Upload Project, set the main
  document to journal_manuscript_v18.tex, recompile. (Run twice so natbib
  citations resolve; Overleaf does this automatically.)
- Command line: pdflatex journal_manuscript_v18.tex  (x2)

## Contents
- journal_manuscript_v18.tex        main source (main document)
- journal_manuscript_v18_refs.tex   reference list (input by the main file)
- journal_manuscript_v18_refs.bib   underlying BibTeX database (not required
  for compilation; included for editorial source completeness)
- m1_m3/, alexandrov_bridge/, association_robustness/  figure PNGs at the
  exact relative paths used by \includegraphics

## Journal of Theoretical Biology submission notes (Guide for Authors,
## verified live 2026-09-21)
- Article type: Regular Article.
- Abstract: 249 words (JTB cap: "does not exceed 250 words"), in two
  paragraphs (theory; biology).
- Keywords: 7 (JTB range 1-7), ending with 'path dependence'.
- Highlights: required by JTB as a separate editable file with
  'highlights' in the file name; provided in the repository at
  download/highlights_jtb.docx (5 bullets, each <= 85 characters incl.
  spaces, featuring the biological applications and the theoretical
  advancement). Upload it as its own file in the submission system.
- CRediT authorship contribution statement: included in the manuscript
  backmatter (required by JTB; single author, roles listed).
- Declaration of competing interests, funding sources, declaration of
  generative AI use, and the research-data statement: all included in
  the manuscript backmatter; the cover letter
  (download/cover_letter_jtb.md in the repository) carries the full
  disclosures.
- Author identity, affiliation, corresponding e-mail, and ORCID appear on
  the title page (\thanks footnote); e-mail and ORCID are clickable.
- Continuous line numbering is enabled via the lineno package.
- Reference style: author-year (natbib); Elsevier accepts any consistent
  style at first submission ("Your Paper Your Way").
EOF

# ---------- COMPANION (Theory and Applications of Categories) ----------
C=$STAGE/companion
cp scripts/companion_categorical_v10.tex    "$C/"
cp scripts/companion_refs_v10.bib       "$C/"
cp download/lipschitz_constants_per_optic.png   "$C/"
cp download/cptc_zeno_contraction.png           "$C/"
cp download/inverse_limit_raf_hasse.png         "$C/"
cp download/inverse_limit_raf_extended_hasse.png "$C/"
cp download/claim_f_holonomy_plot.png           "$C/"
cp download/claims_ae_n4_nonabelian.png         "$C/"
cp download/claim_d_heavytail_stress.png        "$C/"
cp download/levy_stable_3half_derivation.png    "$C/"
cp download/claim_g_zeno_plot.png               "$C/"
cp download/t_iteration_convergence_plot.png     "$C/"
cp download/t_iteration_robustness_extension_axis_aligned.png "$C/"
cp download/t_iteration_robustness_extension_rotated.png      "$C/"
cat > "$C/README.md" << 'EOF'
# Companion manuscript — Theory and Applications of Categories
# Compile-ready standalone package

Title: A Geometric and Category-Theoretic Theory of Viability: How
Sequential Adaptations Induce Path-Dependent Risk

## How to compile
- Overleaf: upload this ZIP via New Project -> Upload Project, set the main
  document to companion_categorical_v10.tex, recompile (pdflatex + bibtex +
  pdflatex x2; Overleaf runs this automatically).
- Command line:
    pdflatex companion_categorical_v10.tex
    bibtex   companion_categorical_v10
    pdflatex companion_categorical_v10.tex
    pdflatex companion_categorical_v10.tex

## Contents
- companion_categorical_v10.tex  main source (main document)
- companion_refs_v10.bib BibTeX database (required by \bibliography)
- 12 figure PNGs at the flat paths used by \includegraphics

## Submission route (TAC author information)
- Initial submission: email the compiled PDF to one Editorial Board member
  (not the Managing Editor or TeXnical editors), cc tac@mta.ca. The cover
  letter (download/cover_letter_tac.md in the repository) is addressed to
  the chosen Transmitting Editor.
- Review model: not anonymized (no double-blind option at TAC); author
  identity is on the paper.
- Keywords and AMS 2020 Subject Classification (18D05; 18N99; 92B05) are
  included per TAC's external-indexing requirements; the final accepted
  version will be reformatted with the journal's tac.cls (12pt).
EOF

# ---------- ZIP ----------
OUT=/home/z/my-project/metabolic-curvature-measure/download
rm -f "$OUT/submission_main_jtb.zip" "$OUT/submission_companion_tac.zip"
(cd "$STAGE/main"      && zip -qr "$OUT/submission_main_jtb.zip" .)
(cd "$STAGE/companion" && zip -qr "$OUT/submission_companion_tac.zip" .)
cd /home/z/my-project/metabolic-curvature-measure

# download PDF copy (byte-identical to the scripts build)
cp scripts/journal_manuscript_v18.pdf download/journal_manuscript_v18.pdf

echo "=== ZIP contents (main) ==="
unzip -l download/submission_main_jtb.zip
echo "=== ZIP contents (companion) ==="
unzip -l download/submission_companion_tac.zip

# ---------- Standalone compile verification (fresh dirs) ----------
rm -rf /home/z/my-project/metabolic-curvature-measure/scripts/zipcheck_v21 && mkdir -p /home/z/my-project/metabolic-curvature-measure/scripts/zipcheck_v21/main /home/z/my-project/metabolic-curvature-measure/scripts/zipcheck_v21/companion
unzip -q download/submission_main_jtb.zip -d /home/z/my-project/metabolic-curvature-measure/scripts/zipcheck_v21/main
unzip -q download/submission_companion_tac.zip -d /home/z/my-project/metabolic-curvature-measure/scripts/zipcheck_v21/companion
echo "=== fresh-dir compile: main v18 ==="
(cd /home/z/my-project/metabolic-curvature-measure/scripts/zipcheck_v21/main && tectonic journal_manuscript_v18.tex 2>&1 | tail -2 && \
 pdfinfo journal_manuscript_v18.pdf | grep Pages)
echo "=== fresh-dir compile: companion v10 ==="
(cd /home/z/my-project/metabolic-curvature-measure/scripts/zipcheck_v21/companion && tectonic companion_categorical_v10.tex 2>&1 | tail -2 && \
 pdfinfo companion_categorical_v10.pdf | grep Pages)
echo "ALL DONE"
